### ISSUE TITLE
Train Multi Gpu

### ISSUE THREAD

**Issue by mehrazi** [caojiangxia/BiGI#8]
Thanks for your great repo.
I tried to train the model for a big graph (about 7M edges in training data).
When I was Training on a single GPU, training time wasn't efficient, so I decided to try multi-gpu, but I got this error:

``` Traceback (most recent call last):
  File "/home/BiGI/BiGI_src/train_rec.py", line 163, in <module>
    loss = trainer.reconstruct(UV, VU, adj, corruption_UV, corruption_VU, fake_adj, user_feature, item_feature, batch)  # [ [user_list], [item_list], [neg_item_list] ]
  File "/home/BiGI/BiGI_src/model/trainer.py", line 152, in reconstruct
    self.update_bipartite(user_feature, item_feature, CUV, CVU, fake_adj, fake = 1)
  File "/home/BiGI/BiGI_src/model/trainer.py", line 131, in update_bipartite
    self.user_hidden_out, self.item_hidden_out = self.model(user_feature, item_feature, UV_adj, VU_adj, adj)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 158, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 175, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 44, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter
    res = scatter_map(inputs)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 23, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 19, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 96, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 189, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: Tensors of type SparseTensorImpl do not have strides

Process finished with exit code 1 
```

How do you train the model on large graphs? Do you have any idea or code for multi-GPU training?

**Comment by caojiangxia** [comment]
Hello~, the neighboring sampling method (SAGE) is effective for fast training speed under the very large graph, but I do not implement it in this version (I am trained BiGI 1-2 weeks for convergence in ML-10M.)

**Comment by mehrdadazizi72** [comment]
Thanks for your reply.

**Comment by mehrazi** [comment]
Thanks for your reply.
can you share your hardware details for training?
I have been training my data on an Nvidia-1080 GPU, with this config:
   
        Running with the following configs:
        data_dir : dataset/dblp/
        weight : False
        sparse : False
        GNN : 1
        feature_dim : 100
        hidden_dim : 100
        dropout : 0.3
        optim : adam
        lr : 0.001
        lr_decay : 0.9
        weight_decay : 0.0005
        decay_epoch : 5
        leakey : 0.1
        cpu : False
        cuda : True
        margin : 0.3
        lambda : 0.3
        negative : 1
        DGI : True
        attention : True
        struct : True
        struct_rate : 0.0001
        num_epoch : 500
        min_neighbor : 3
        batch_size : 4
        log_step : 200
        log : logs.txt
        save_epoch : 50
        save_dir : ./saved_models
        id : 00
        topn : 10
        seed : 2040
        load : False
        model_file : None
        save_node_feature : True
        wiki : False
        number_user : 350631
        number_item : 161648
        model_save_dir : ./saved_models/00

it costs a very long time to train (about 6-7 seconds for each batch)
Do you mind any idea for improving training speed?

**Comment by caojiangxia** [comment]
Hi, I recommend using PyG or DGL projects for large-scale graph training. 

By the way, you can try my latest work UniCDR in one-domain setting~ (simply modify the running command), the codes are released at [here](https://github.com/cjx96/UniCDR).

**Comment by mehrazi** [comment]
Thanks for your recommendations 
I'll try them
